[tools]
elixir = "latest"
elixir-ls = "latest"
elm = "latest"
erlang = "latest"
gleam = "latest"
go = "latest"
ghcup = "latest"
node = "latest"
opam = "latest"
python = "latest"
# rust = "latest"
# rust-analyzer = "latest"
shfmt = "latest"
starship = "latest"
uv = "latest"
yazi = "latest"
zig = "latest"
